# Generated by Django 2.0.2 on 2019-09-28 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='acao_documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=128, null=True, verbose_name='titulo')),
                ('descricao', models.CharField(blank=True, max_length=128, null=True, verbose_name='descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos_processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('arquivo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=128, null=True, verbose_name='titulo')),
                ('descricao', models.CharField(blank=True, max_length=128, null=True, verbose_name='descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone_celular', models.CharField(blank=True, help_text='Número do telefone celular no formato(00)0000-0000', max_length=14, null=True, verbose_name='Telefone fixo ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='prazo_processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_original', models.DateField(blank=True, null=True, verbose_name='prazo original')),
                ('pedido_prazo', models.BooleanField(default=False)),
                ('justificativa', models.CharField(blank=True, max_length=500, null=True, verbose_name='justificativa do prazo')),
                ('novo_prazo', models.DateField(blank=True, null=True, verbose_name='Novo Prazo')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15, verbose_name='numero do processo')),
                ('data_criaçao', models.DateField(auto_now_add=True)),
                ('id_interessado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interessados', to='app_g1.Pessoa')),
                ('id_investigado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigados', to='app_g1.Pessoa')),
                ('usuario_criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=128, null=True, verbose_name='titulo')),
                ('descricao', models.CharField(blank=True, max_length=128, null=True, verbose_name='descricao')),
            ],
        ),
        migrations.CreateModel(
            name='tramitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('id_departamento_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Departamento')),
                ('id_departamento_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_atual', to='app_g1.Departamento')),
                ('id_departamento_posterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posterior_departamento', to='app_g1.Departamento')),
                ('id_orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Orgao')),
            ],
        ),
        migrations.AddField(
            model_name='prazo_processo',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Processo'),
        ),
        migrations.AddField(
            model_name='documentos_processo',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Processo'),
        ),
        migrations.AddField(
            model_name='documentos_processo',
            name='tipo_arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Tipos_documentos'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Orgao'),
        ),
        migrations.AddField(
            model_name='acao_documento',
            name='tipo_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Tipos_documentos'),
        ),
    ]
