# Generated by Django 2.0.2 on 2019-10-05 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_g1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=128, null=True, verbose_name='numero')),
                ('data_envio', models.DateField(blank=True, null=True, verbose_name='prazo original')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=128, null=True, verbose_name='numero')),
            ],
        ),
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=128, null=True, verbose_name='numero')),
            ],
        ),
        migrations.RemoveField(
            model_name='acao_documento',
            name='tipo_doc',
        ),
        migrations.RemoveField(
            model_name='tramitacao',
            name='id_departamento_anterior',
        ),
        migrations.RemoveField(
            model_name='tramitacao',
            name='id_departamento_atual',
        ),
        migrations.RemoveField(
            model_name='tramitacao',
            name='id_departamento_posterior',
        ),
        migrations.AddField(
            model_name='documentos_processo',
            name='numero',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='numero'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='funcionario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processo',
            name='id_departamento_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Departamento'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='data_movimentacao',
            field=models.DateField(blank=True, null=True, verbose_name='Novo Prazo'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='id_departamento_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_atual', to='app_g1.Departamento'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='id_departamento_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_origem', to='app_g1.Departamento'),
        ),
        migrations.DeleteModel(
            name='acao_documento',
        ),
        migrations.AddField(
            model_name='portaria',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Documentos_processo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Documentos_processo'),
        ),
        migrations.AddField(
            model_name='envio',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_g1.Documentos_processo'),
        ),
        migrations.AddField(
            model_name='envio',
            name='id_departamento_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_onde_foi_enviado', to='app_g1.Departamento'),
        ),
    ]
